### ISSUE TITLE
Fixed row on tablet and mobile as well as desktop

### ISSUE THREAD

**Issue by Aearyl** [beaverbuilder/feature-requests#116]
Hi, 

Designed my site aearyl.com and realised the 'fixed' row which was working fine on desktop does not work on tablet or mobile. 

On mobile and tablet it just scrolls, and I need it to function in the same way as it does on the desktop. 

I assumed there was a bug in the system which is why it didn't work, but then have been told it is not part of the functionality of BB, which I find astounding for such a simple feature. 

I had designed the website around the ability for certain rows to be fixed on all devices, so that other rows would scroll over them as they do on the desktop. So not to have the feature will mean a time consuming re-design. 

Please can you fix this in bb so the 'fixed' non scrollable row works on all devices, and not just the desktop. 

Thanks 
Daryl

**Comment by Dannyholt** [comment]
Hi @Aearyl 

Are you referring to row background images set to `fixed`? If so, then this isn't possible as mobile device such as smartphones and tablets don't support `background-attachment: fixed;` which is what fixed backgrounds use for this effect. :(

**Comment by Aearyl** [comment]
Thanks Danny, They seem to have managed it here (well somewhat) ? https://www.pb-creative.com/workOr are they using a different technology? Kind regards Daryl ---------------------------------Daryl JonesCreative Director aearyl.com07719 095 0770800 634 9272----------------------------------------- Original message --------From: Danny <notifications@github.com>Date: Thu, 4 Mar 2021, 22:31To: beaverbuilder/feature-requests <feature-requests@noreply.github.com>Cc: Aearyl <Daryl@aearyl.com>, Mention <mention@noreply.github.com>Subject: Re: [beaverbuilder/feature-requests] Fixed row on tablet and mobile as well as desktop (#116)
Hi @Aearyl
Are you referring to row background images set to fixed? If so, then this isn't possible as mobile device such as smartphones and tablets don't support background-attachment: fixed; which is what fixed backgrounds use for this effect. :(

**Comment by Dannyholt** [comment]
That is something different. For example, they're not using `background-attachment:fixed` but `position:fixed` with `<img>` tags. :)

**Comment by Aearyl** [comment]
Thanks Danny, I may give that a go :-) ---------------------------------Daryl JonesCreative Director aearyl.com07719 095 0770800 634 9272----------------------------------------- Original message --------From: Danny <notifications@github.com>Date: Thu, 4 Mar 2021, 23:36To: beaverbuilder/feature-requests <feature-requests@noreply.github.com>Cc: Aearyl <Daryl@aearyl.com>, Mention <mention@noreply.github.com>Subject: Re: [beaverbuilder/feature-requests] Fixed row on tablet and mobile as well as desktop (#116)
That is something different. For example, they're not using background-attachment:fixed but position:fixed with <img> tags. :)
