### ISSUE TITLE
Deeper Metabox.io Integration

### ISSUE THREAD

**Issue by iamandrewpeters** [beaverbuilder/feature-requests#124]
**Is your feature request related to a problem? Please describe.**
Problem, not per se. 

**Describe the solution you'd like**
ACF has integrations for fields groups, repeaters, etc. I would love to see similar integrations created to use nested fields, field groups, repeater fields, etc for the Metabox plugin.

**Describe alternatives you've considered**
Considered reverting back to ACF, but Metabox does so much that ACF doesn't (well beyond just meta box functionality) that switching back would be a hindrance. 

**Additional context**

**Comment by codente** [comment]
Metabox built the compatibility/integration for Themer in their plugins so this request should be directed at them.

**Comment by iamandrewpeters** [comment]
Gotcha. That was super quick. haha.

**Comment by codente** [comment]
Ha, we get notifications in our slack and I just happened to see it!
