### ISSUE TITLE
ACF: Fetch repeater field from option pages

### ISSUE THREAD

**Issue by Florrpan** [beaverbuilder/feature-requests#125]
**The problem**
The problem right now is that you can only fetch repeater field information if it is connected to a post type, I.E; A page of a post.

**Reapeater fields from option pages**
Having the ability to fetch repeater fields from option pages.

**The solution**
Give us the ability to tell Themer from where we want to fetch the repeater fields from just like all the other custom fields.

**Additional context**
We have the ability to get data from many other custom fields from an option page. Having the repeater field on option page  would allow us to make more powerful solutions and applications for customers.

**Comment by Florrpan** [comment]
@codente I believe PODS any many other custom field plugins have repeaters. Do the function need to be specific?

**Comment by codente** [comment]
@Florrpan Yes, our integration is with ACF.  Pods provides Themer support in their own plugin so the support would have to be added there.  And Pods does not have repeaters yet but it's on the roadmap.

**Comment by codente** [comment]
You can actually already to this.  Example code:

The `type='option'` being key here
```
[wpbb-acf-repeater type='option' name='repeat']
[wpbb site:acf_option type='text' name='firstname']
[wpbb site:acf_option type='text' name='lastname']
[/wpbb-acf-repeater]
```

**Comment by Dannyholt** [comment]
@Florrpan 

We have this documented.

https://docs.wpbeaverbuilder.com/beaver-themer/field-connections/connections-to-acf/use-acf-repeater-fields-themer/#acf-options-page

**Comment by codente** [comment]
No, it wasn't - we documented it because of this and the FB thread. Letting you and others who may come across this know where to find it in the docs.
