### ISSUE TITLE
Support for installation via Composer

### ISSUE THREAD

**Issue by ethanclevenger91** [beaverbuilder/feature-requests#134]
**Is your feature request related to a problem? Please describe.**
There's a growing community of developers using Composer to manage WordPress installs through frameworks like [Bedrock](https://github.com/roots/bedrock). Composer-based installation of such tools makes license management simpler, git repositories cleaner, and automated updates more reliable.

**Describe the solution you'd like**
All Beaver products set up with Composer-driven options for installation. See the [Delicious Brains](https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/) products for an example.

**Comment by Pross** [comment]
Composer support was added a couple of years ago!
https://docs.wpbeaverbuilder.com/beaver-builder/developer/tutorials-guides/install-beaver-builder-via-composer/

**Comment by ethanclevenger91** [comment]
@Pross Holy cow how am I just now seeing this. Clearly should have pinged the Slack first.

**Comment by ethanclevenger91** [comment]
@Pross I am a little uncomfortable with the idea of committing our BB Key. Obviously we can move the custom repo definition to a global composer.json file instead of the one in our WP install, but then another dev would get an ambiguous "package not found" message when they tried to get set up.

Support for something like [http-basic authentication via auth.json](https://getcomposer.org/doc/articles/authentication-for-private-packages.md) might be a better approach.

**Comment by Pross** [comment]
Just use the `composer config --global repositories.beaver-builder` method, then its available to everyone on the server. Switching to http auth would mean total rewrite and I dont think the server code we have even supports it.

**Comment by ethanclevenger91** [comment]
@Pross All my clients are on their own, isolated VPS. But yeah, it's totally doable. I just think there's value in separating auth from the rest of the configuration.

**Comment by Pross** [comment]
It no different than having to add keys to _knownhosts_ files for users to login ;)

**Comment by ethanclevenger91** [comment]
@Pross I disagree.

Say I'm a fresh developer on a project in the worst case scenario - I've inherited a client project and have no contact with the original developer. I just got a git repository (or worse, FTP'd down the site, heh). But I see a `composer.json`, and I know what that means. I `git clone` if necessary and run `composer install`. Let's assume I haven't configured anything yet for Beaver Builder - maybe I've never had a BB project before. The error message from Composer is going to be something like...

`The package beaver-builder/bb-plugin-pro could not be found in any installable version something something something`

At that point, there's not really any guidance. Was it removed from a Composer repository configured in the project? Do I need to set up a repository globally? What's a beaver builder? Hopefully the requirements are in the README. Alternatively, they probably Google `beaver-builder/bb-plugin-pro`, which ought to turn up the BB documentation. But they have to do some digging.

Alternatively, consider that same scenario with the Beaver Builder repository configured in the project's `composer.json` and authentication handled via an uncommitted `auth.json` (global or otherwise) There won't even be an error message at this scenario. Instead, Composer will present the repository that needs authenticated and ask for credentials, which it will save for later in `auth.json`. It's very clear what's missing for the developer to get this installed. Metaphorically, they only need a password - not the login URL _and_ a password. IMO, the developer experience is stronger this way.

It's a small thing, but I think `composer.json` should be explicit about where everything for the project is coming from.

**Comment by ethanclevenger91** [comment]
Also encourages use of API keys rather than the license key (support for which would obviously have to be built on the BB end). API keys can be revoked to remove access or rotated and updated. The license key, so far as I know, cannot.

**Comment by Pross** [comment]
It is what it is im afraid. You should come over to the slack if you want to discuss this further and I'll go into detail why passwords cant work for our setup, this isnt the place.
