### ISSUE TITLE
Featured Image in Post Navigation

### ISSUE THREAD

**Issue by morgangrip** [beaverbuilder/feature-requests#138]
I'm looking for a solution to show the Featured Image in the Post Navigation Module, Next and Previous. That sure would be a nice feature to have.

**Comment by Pross** [comment]
Its already a feature, you can use the `fl_theme_builder_post_nav` filter to change the args passed to the WP function that renders the navigation then armed with that you can use one of the 1000s of code snippets Google will find.
Example:
```
add_filter( 'fl_theme_builder_post_nav', function( $args ) {

	$next_post     = get_next_post();
	$previous_post = get_previous_post();
	if ( isset( $next_post->ID ) ) {
		$args['next_text'] = '<span class="post-title">%title</span>' . get_the_post_thumbnail( $next_post->ID, 'thumbnail' );
	}
	if ( isset( $previous_post->ID ) ) {
		$args['prev_text'] = '<span class="post-title">%title</span>' . get_the_post_thumbnail( $previous_post->ID, 'thumbnail' );
	}
	return $args;
} );
```
