### ISSUE TITLE
Themer Support for "Post Element Class" field in Post Module

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#144]
I would like to be able to dynamically add a custom class to a post container in the Post Module

**Describe the solution you'd like**
Add Themer shortcode support to the field "Post Element Class" in the Post Module

**Describe alternatives you've considered**
The only current way to add custom classes to a post container is to add it via a custom taxonomy - which isn't always the correct solution

**Additional context**
Add Themer + icon for this field
![Screen Shot 2021-04-28 at 17 18 18](https://user-images.githubusercontent.com/19413506/116479983-27922b80-a846-11eb-8f03-4deecaccb116.jpg)

**Comment by zackpyle** [comment]
@codente Just wanted to check in on this again? Would really love to be able to add wpbb shortcodes here

**Comment by Pross** [comment]
You can already add shortcodes to basically ANY setting that allows you to type in it, what shortcodes have you tried?
https://a.cl.ly/Kou9eZAP
https://a.cl.ly/jkuAneW1

**Comment by zackpyle** [comment]
@Pross I'm trying to add an ACF field:
![Screen Shot 2023-03-10 at 14 14 15](https://user-images.githubusercontent.com/19413506/224418962-ce39e22b-41ff-4cb7-8dfc-001c932303ec.jpg)
It doesn't render the shortcode. It just strips it out:
![Screen Shot 2023-03-10 at 14 13 06](https://user-images.githubusercontent.com/19413506/224418799-6431d20e-20a5-4d39-8573-acd67851f74f.jpg)

**Comment by Pross** [comment]
Try removing the quotes, perhaps youre shortcode does not output a string, perhaps it outputs html? Perhaps esc_attr is stripping whatever is outputted, honestly it works

**Comment by zackpyle** [comment]
Yup, that works by removing the quotes. So this isn't "solved" but this is a good workaround for now.

Is it similar to what was happening when I tried to add an wpbb shortcode to the class field and you figured out the issue?

**Comment by Pross** [comment]
Basically, all settings in BB are JSON based quotes and things like that can cause issues.

**Comment by Pross** [comment]
In the case of your shortcode you do not need ANY quotes at all because all the params have no spaces
example
[someshortcode foo=hello world] would not work, because there is a space

**Comment by zackpyle** [comment]
@codente Should have been tagged as **Live** not **In Progress** since it was released in 2.6.3 today, no?
