### ISSUE TITLE
Output WP Users in a grid

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#148]
**Is your feature request related to a problem? Please describe.**
I would like to be able to output WP users just like I can with posts

**Describe the solution you'd like**
I would like a Users module (exactly like Posts module but using WP_User_Query). And have filters like filtering by WP User Role. And then style the output using Themer in a custom layout

**Describe alternatives you've considered**
Currently need to write a php user query and output the results that way

**Additional context**
https://developer.wordpress.org/reference/functions/get_users/

**Comment by vectorba** [comment]
+1 for this feature.

**Comment by zackpyle** [comment]
@vectorba You need to react to my feature with a 👍🏻  for your vote to count

**Comment by gbissland** [comment]
Voted: This would be useful. We've need this for 3 sites/clients this last year.

We've ended up using the User Post type add-on with FacetWP premium, which essentially creates a post type for the users then post grids work based on that. WPGridBuilder also has this, but native in BB would be a good useful addition.

**Comment by zackpyle** [comment]
For anyone needing this, I now do this with Loops & Logic ;)
