### ISSUE TITLE
Can we add moosend to the subscription module please or allow other services to be added.

### ISSUE THREAD

**Issue by JBluelight** [beaverbuilder/feature-requests#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JBluelight** [comment]
Just would like moosend added to the subscription module or the option to add a service.

**Comment by codente** [comment]
In 2.5, there will be a filter available to add services.  2.5 is currently in Alpha :)
