### ISSUE TITLE
Issues with insertion of ACF fields into a page when they are "sourced" from other posts 

### ISSUE THREAD

**Issue by IOR-code** [beaverbuilder/feature-requests#156]
**Desired workflow: be able to insert "featured ACF sections" from other posts into a page**
The objective is to source select ACF fields including texts, images, shortcodes etc. from other posts (Articles/source posts) and to insert them into a Front page (the destination page), in order to give a compelling preview of the full article.

**The problem: SHORTCODES are not preprocessed before reaching the destination page**
In most cases shortcodes contained within ACF custom fields in the post/Articles are NOT executed remotely. They get mixed up when they reach the destination Front page and process values from the equivalent ACF fields present in the Front page.

![image](https://user-images.githubusercontent.com/84310443/120331137-c1d60b00-c2ed-11eb-89fa-1b4a6a68f36d.png)

**A convoluted solution exists, but cannot be used in practice**
Grid based lay out plugins such as Content Views or Beaver Builder “insert Posts”, handle multiple posts in bulk and seem to perform the remote shortcode execution and rendering properly. The grid solutions manage to pre-process the shortcodes in the source posts. So there is already available code in other workflows that offers a solution to this preprocessing issue. 

**Desired outcome: 1/ a shortcode to insert "remote" ACF fields  2/ Preprocessing code **
The challenge is to identify how to make the solution consistent ad pervasive across all types of inserts in a simple manner such as this:  **[ insertRemoteACF  id='35400'   my_ACF_field='featured' ]** where id=' '  is the id number of the remote post and 'featured is the name of the select ACF custom field.

**Comment by codente** [comment]
Duplicate of #61
