### ISSUE TITLE
Button Group module - widths

### ISSUE THREAD

**Issue by bostonchic** [beaverbuilder/feature-requests#166]
When using Button Group module, would be nice if the buttons were equal width regardless of content/characters.

**Comment by codente** [comment]
This option does already exist in the main style tab. This width will be used for all buttons if set.

![Image 2021-07-06 at 12 59 24 PM](https://user-images.githubusercontent.com/2265866/124646282-107d4480-de5a-11eb-8d62-dbeb440bdbc9.jpg)

**Comment by bostonchic** [comment]
That doesn't help for an issue if I want larger buttons on the front page
or a particular area.  I'm using the Button Group Module.


*Cyndi Papia, Website Specialist*
Office To-Go <https://OfficeTo-Go.com>
888-851-4426 <+18888514426>
New Bern, NC 28562

** PLEASE *DO NOT *SEND LOGINS OR PASSWORDS VIA EMAIL, IT'S NOT SECURE.**
USE DROPBOX OR PRIVNOTE <https://privnote.com/>.
*Join Me on Facebook* <https://www.facebook.com/officetogo/>

* Phone calls/consults must be scheduled so I give you the full attention
you deserve.

**Comment by bostonchic** [comment]
I'm using the Group Button Module, the buttons on it are larger than the buttons throughout.

**Comment by codente** [comment]
This option is in the button group module, not the customizer.

**Comment by bostonchic** [comment]
I just am not seeing it.  It's not in the style in the button group or in advanced.  :(

**Comment by codente** [comment]
My apologies.  It's in the Global Style in the Button Group ( the main style tab where you add buttons, not the style tab for individual buttons).

But we added this in 2.5 (currently in beta) so this feature is coming.  We expect one more beta before stable.
