### ISSUE TITLE
Please add FluentCRM to the Subscribe module

### ISSUE THREAD

**Issue by cvconley** [beaverbuilder/feature-requests#171]
[FluentCRM](https://fluentcrm.com/) is a growing, quality CRM integrated into wordpress. (similar to Groundhogg.io)

I do not see it as an integration in the Subscribe module.

Please consider adding it to your supported integrations.

Thank you!

**Comment by codente** [comment]
Groundhogg provided the code for their integration actually.  And in 2.5, users will be able to add their own (and other plugins too).  As a result of that and recent issues we've had where services are upgrading their APIs without backwards compatibility and adding other breaking changes, we've decided to hold off on any other integrations that we add.
