### ISSUE TITLE
Deprecated Warning when using wordpress 5.8

### ISSUE THREAD

**Issue by llopen-sourcell** [beaverbuilder/feature-requests#173]
when updating to worpdress 5.8, and if WP_DEEBUG is true, then a warning is thrown saying block_editor_preload_paths is deprecated use block_editor_rest_api_preload_paths instead

**Comment by codente** [comment]
This is not a bug report page.  This is a feature request page.   Also, we released 2.4.2.5 yesterday and it has a fix for this notice.
