### ISSUE TITLE
`[wpbb post:woocommerce_product_price]` uses global $post data inside loop of Posts module

### ISSUE THREAD

**Issue by jeremylind** [beaverbuilder/feature-requests#174]
Set up multiple products
On a singe product themer layout, add a Posts module that loads other or related products
Set the Posts module layout to Custom
Include the `[wpbb post:woocommerce_product_price]` shortcode in the custom layout.

The shortcode renders the price for the main product, not the product in the loop.

On line 73 in `/wp-content/plugins/bb-theme-builder/extensions/woocommerce/classes/class-fl-page-data.woocommerce.php`, the function checks if the page is an archive. Otherwise, it loads the single product price template. This does not account for the product price being rendered in a loop not on an archive page.

**Comment by Dannyholt** [comment]
Can you provide a link to site which has this issue as I am unable to replicate the issue.

![](https://p74.tr4.n0.cdn.getcloudapp.com/items/kpuDpem1/bdf11860-7186-4ba9-a492-0aa4a0235c0a.jpg)

**Comment by jeremylind** [comment]
The site is in development, so I don't have a preview available. Attached is a screenshot of my set up.
<img width="2672" alt="Screen Shot 2021-07-28 at 9 39 06 AM" src="https://user-images.githubusercontent.com/11154028/127362644-321f1037-a982-4ef5-9d79-1ed01122d322.png">

**Comment by Dannyholt** [comment]
I'm going to close this as none of our team can replicate the issue. It is likely either some custom loop code is causing the issue or a third-party plugin.

Try disabling plugin all plugins except for BB, Themer and see if the issue persists. If it does, switch themes so your custom code isn't load then check again.

If none of the above work, open a ticket.

Also, this isn't a feature request, but a support request. Therefore, in future please, open a ticket. :)

**Comment by jeremylind** [comment]
This is still an issue with all plugins and child themes disabled (except for BB, Themer and WooCommerce). I referenced the file and line where I see the issue. Running a PHP debugger, I can see the request pass through that function, and the logic does not accommodate the use case :)

**Comment by Pross** [comment]
Please open a ticket. I was also unable to replicate this. It makes it even harder to debug your local only site. Export the site and send me the export file in your ticket and I'll retest it.
