### ISSUE TITLE
Beaver Themer Header and Footer layouts based on screen size

### ISSUE THREAD

**Issue by spidercreations** [beaverbuilder/feature-requests#175]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
My thought is to allow for Themer layouts to not just be based on pages, posts or other location, but to allow for different layouts to be displayed based on screen size. An example would be to have a different header display on the home page for mobile devices.

**Describe alternatives you've considered**
What I'm doing now is setting up footer and header rows and setting the visibility breakpoints for each row. I may have two or three rows that need to be configured to display for a full screen browser, then I add a row or two (or whatever) to display a different header for mobile devices. If we wanted to have a different view for a tablet, that would require a third set of rows with the visibility set differently. This is possible, but clients are having a tough time editing and they frequently mess it up. Would be nice to have a specific Themer Layout for the header and set it for mobile, tablet and full screen.

**Additional context**
None really.

**Comment by codente** [comment]
We discussed this recently and decided against it so while I'd never say never, it's not currently on our roadmap or something we are considering. Due to that, I'm closing this but will re-open if something changes there.
