### ISSUE TITLE
I'd like to be able to conditionally hide and show comments modules when the wordpress core setting for "Allow discussion on this post" is true

### ISSUE THREAD

**Issue by marktenney** [beaverbuilder/feature-requests#176]
This appears like a bug or broken functionality to our clients. When they deselect the "allow commenting" feature in wp-admin, the comments area is still visible and accessible to users. I would like to be able to hide or show the comment form based on that setting.

Since that setting doesn't use a custom field to store its value, I can't use the normal conditional logic features to support this functionality.

The only alternative I've considered is to use my own custom field to manage comments on posts, but that seems unnecessary and heavy-handed. I think Beaver Themer should support this as part of its core functionality.

**Comment by marktenney** [comment]
@Pross I think I mentioned this one to you earlier this year in slack and you said something about getting this on the radar for development. Is this something that will be added anytime soon? (To recap, the "Allow Commenting" feature in WP Core doesn't work when using a Themer Layout to create the single post view.)

Thank you!

**Comment by Pross** [comment]
Comments status logic rule will be in 1.4.1 of Themer. You'll be able to show/hide based on whether comments are open/closed on the post.

**Comment by marktenney** [comment]
Awesome! Thank you so much!

**Comment by Pross** [comment]
Also you dont need a custom field, you can use the node visibility filter... check the post comments status and hide or show the node.
