### ISSUE TITLE
Filters to Modify Module Settings

### ISSUE THREAD

**Issue by jacksonwp** [beaverbuilder/feature-requests#177]
Please provide a filter that we can use to modify module settings before the module is rendered (bonus points for being able to filter the options that appear in the module).

As an example in the gallery module, if you use the masonry layout, there's only 3 settings for column width that can be quite limiting. We end up having to modify the select dropdown option value in the inspector before saving the module.

I realize I can create my own module but it seems a bit ridiculous when I'm just trying to change the column width value from 300 to 248 to get the width I need for my layout.

**Comment by codente** [comment]
If I understand correctly, we already have a filter for what you'd like to do here.

Example here: https://gist.github.com/Pross/3b41044dd8358b908a727d2b53f29bf9

This would randomize animations for modules on each page load.
