### ISSUE TITLE
Copy Settings/Styles for Columns or Rows

### ISSUE THREAD

**Issue by voodoocreativellc** [beaverbuilder/feature-requests#210]
Can we get the option to copy styles/settings for columns and rows.

**Comment by codente** [comment]
Probably covered under #75 but I'll leave this open unless/until we decide what we're doing here.  Improving copy/paste is something we're looking at for 2.7, maybe even 2.6 :)

**Comment by voodoocreativellc** [comment]
Great. A specific use case is when I decide the padding of the columns should be 30px instead of 20px. Have to go into each one and change. I've started using CSS to alleviate this, but would be a nice feature.

**Comment by zackpyle** [comment]
@codente This is fully implemented, correct?

**Comment by codente** [comment]
Yes it is!
