### ISSUE TITLE
Open links in a new tab/window

### ISSUE THREAD

**Issue by mariafernandez** [beaverbuilder/feature-requests#217]
I'd like to be able to open the links inside modules in a new tab or a new window.

The aim of this is to be able to retain visitors on my site when they click on a link that takes them to an external site. And also to retain them on a page with header and footer when they click on a link that takes them to a squeeze page.

**Comment by codente** [comment]
@mariafernandez what modules that have link fields are you not seeing this option for?

Heading Module link field has a new window option
![image](https://user-images.githubusercontent.com/2265866/150539770-cfa2f1e6-9d56-4b68-b34c-cd9436c91ef8.png)

Button Module
<img width="759" alt="CleanShot 2022-01-21 at 08 01 03@2x" src="https://user-images.githubusercontent.com/2265866/150539816-59aa0a11-6e52-43fd-899a-225d6946f610.png">

**Comment by mariafernandez** [comment]
Hi,

The posts module doesn't have that essential option.

For example here: https://learnenglishwithmaria.com/

and here: https://learnenglishwithmaria.com/course-grid/

How can I get my courses to open in the new tab? That feature is essential
because some of those links take you to a squeeze page with no navigation
buttons.

Maria Fernandez
*learnenglishwithmaria.com* <https://learnenglishwithmaria.com/>

**Comment by codente** [comment]
The posts module pulls in posts from your own site and those post titles are linked which are internal links.   It's all handled dynamically and is not something where you can enter a specific URL for each post that is pulled into the posts module where you could add an option for opening in a new window.   If we added such an option it would have to apply to all posts that are pulled into the posts module.

**Comment by mariafernandez** [comment]
HI,

Which module should I use to create a page identical to this with the links
of my choice opening in a new tab?: https://learnenglishwithmaria.com

The links I'm talking about are obviously the rectangles with the blue text
and image.

Maria Fernandez
*learnenglishwithmaria.com* <https://learnenglishwithmaria.com/>

**Comment by codente** [comment]
As mentioned above, check out the Callout Module.
