### ISSUE TITLE
Split Background Colors / Images

### ISSUE THREAD

**Issue by pixelloop** [beaverbuilder/feature-requests#222]
There's something I have tried to do several times but have never found a workable solution other than using CSS.

.split-bg-1 {
    background: linear-gradient(90deg, #FFFFFF 50%, #EC1D23 50%);
}

I want a row with a color background that's split. I don't want a gradient where it fades, just a white background on the left and red background on the right for example.

I can't do this with two columns where the columns have different backgrounds because that requires me to make the row full width and I want the content within the two columns to follow the same widths as all of the other rows. 

Doing this with margin and padding is a mess and doesn't really work.

This seems a pretty common thing but is very difficult within the BB editor. I think it should be added as an option to the row background settings under the gradient option. 

It would also be good to have it go from top to bottom rather than left to right when the site is in mobile responsive mode.

Thanks

**Comment by Dannyholt** [comment]
The CSS you're using is a gradient and so, you can already do this in Beaver Builder using the gradient row background option.

https://cln.sh/0wgiXo

**Comment by pixelloop** [comment]
Does this also auto adjust to top to bottom? I spoke with BB support and they said neither were possible and I should add it as a feature request.

**Comment by pixelloop** [comment]
Does this also auto adjust to top to bottom? I spoke with BB support and
they said neither were possible and I should add it as a feature request.

Thanks,

David Alexander
Web Designer, Developer & Marketing Consultant
Pixelloop
w: pixelloop.org  e: ***@***.***

ᐧ

**Comment by Dannyholt** [comment]
Im sure what you mean by auto adjust, but if you mean will it fill the row regardless of screen width, then yes. As it is a background.

**Comment by pixelloop** [comment]
Hi Danny

Sorry. no what I mean is, when you go into smaller screens, you don't want to split the screen into left and right as the columns will be top and bottom, so does this gradient effect know to change too? 

Imagine

White text on black background (left side)

Black text on white background (right side)

On mobile these two columns are stacked. If it's black and white divided down the middle then neither will work. So the gradient radius needs to change from 90 degrees to 180 degrees right? Does that happen? If not, I don't think this solution works.

**Comment by Dannyholt** [comment]
There are no responsive toggles for gradients so you would need to use CSS to override the degrees of the gradient for mobile devices.

**Comment by pixelloop** [comment]
Okay so can I keep this feature request open then? or create a new one requesting responsive options for gradients? This is why I have never been able to use the gradients feature in the past.

**Comment by Dannyholt** [comment]
Create a new request and lablel it "Responsive toggle for gradient backgrounds". :)

**Comment by pixelloop** [comment]
Thank you Danny. That's done now. Here's the link

https://github.com/beaverbuilder/feature-requests/issues/223
