### ISSUE TITLE
Add Pressidium to Cache Clearing Tool

### ISSUE THREAD

**Issue by over-engineer** [beaverbuilder/feature-requests#227]
**Is your feature request related to a problem? Please describe.**
Beaver Builder's Cache Clearing Tool doesn't support [Pressidium](https://pressidium.com/).

**Describe the solution you'd like**
It'd be great if Pressidium was added to the Cache Clearing Tool.

This can be done by creating `/extensions/fl-builder-cache-helper/plugins/pressidium.php` with the following content:

```php
<?php
namespace FLCacheClear;

class Pressidium {

    var $name = 'Pressidium Hosting';
    var $url  = 'https://pressidium.com/';

    static function run() {
        if ( ( isset( $_SERVER['PRESSIDIUM_PLATFORM'] ) || getenv( 'PRESSIDIUM_PLATFORM' ) ) && class_exists( '\NinukisCaching' ) ) {
            \NinukisCaching::get_instance()->purgeAllCaches();
        }
    }

}
```

I tested it on a WordPress installation on Pressidium and it works.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by codente** [comment]
@over-engineer Do you work for Pressidium?  We're looking at adding this but would like to actually test it on Pressidium.  If you can arrange that, please reach out via this form: https://www.wpbeaverbuilder.com/contact/.   Select General Inquiry or Feature Suggestion. :). Thanks!

**Comment by codente** [comment]
Added in 2.6 beta.4, just released today :)

**Comment by codente** [comment]
In 2.6. Thanks for the suggestion and the code :)
