### ISSUE TITLE
ACF custom field meta query

### ISSUE THREAD

**Issue by chillybin** [beaverbuilder/feature-requests#23]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I want to create a custom loop in the posts module, but only want to bring out content through a taxonomy query. Say every post that has a checkbox marked true, or every post with a specific value.

**Describe the solution you'd like**
Currently we can filter by author, category, post type, post name. I'd like an option to list all of the ACF fields and to build this into a taxonomy query as part of the loop targeting specific meta keys.

**Describe alternatives you've considered**
Currently I've been building custom shortcodes, which is not idea.

**Additional context**

**Comment by zackpyle** [comment]
@codente Is this feature request the same feature that is currently in Alpha? "Post module filter by custom field"

If so, should be moved to that section of roadmap?

**Comment by codente** [comment]
Currently planned for 2.6.  Out now in the pre-release version of 2.6!

**Comment by codente** [comment]
In 2.6!
