### ISSUE TITLE
Ability to crop featured image by adding "crop" argument in shortcode

### ISSUE THREAD

**Issue by AchalJ** [beaverbuilder/feature-requests#232]
Please make it possible to crop the featured image when adding the "crop" argument to the shortcode [wpbb post:featured_image]

Example:

`[wpbb post:featured_image crop='circle']`

**Comment by pixelloop** [comment]
This is so needed, especially when you want to use the custom style in the posts module.

**Comment by Pross** [comment]
This isnt possible. The photo module does cropping and adds CSS from that module to make the cropped images into circles etc. The shortcode uses the core WP function `get_the_post_thumbnail()` to fetch the image markup. So if you want custom crop sized images then you need to use https://developer.wordpress.org/reference/functions/add_image_size/ to add your custom size then css to make it circle or whatever you like.

**Comment by pixelloop** [comment]
@Pross 

That's how I have been doing it. I was imagining if the post module from Powerpack "content grid" can do this when custom isn't selected. There must be a way to improve the shortcodes to do the same. I'm not sure what the technical limitation is there.
