### ISSUE TITLE
Structure Tree / Outline QoL Enhancement

### ISSUE THREAD

**Issue by mcneese** [beaverbuilder/feature-requests#234]
**Is your feature request related to a problem? Please describe.**
The outline panel is awesome! It has transformed how I interact with BB. However, in my workflow I typically open the Outline panel and collapse all rows to reorder layouts, quickly get to row settings etc. If i close the panel to adjust something or to get it out of the way and open it again - all the rows have auto expanded again. It's a minor inconvenience to have to collapse them all again.

**Describe the solution you'd like**
It would be nice if the panel "remembered" if certain rows were expanded or collapsed when re-opening or if there was a expand all or collapse all UI.

**Comment by codente** [comment]
We'd definitely like this too! It's definitely on the to do list for a future release.

**Comment by codente** [comment]
Planned for 2.6!

**Comment by codente** [comment]
Expand all/collapse all was added in 2.6 :)
