### ISSUE TITLE
Add the ability to do reverse stacking on Tablet breakpoints

### ISSUE THREAD

**Issue by nomad411** [beaverbuilder/feature-requests#241]
This is asked for from time to time.

Putting it here to let people vote on it.

**Comment by A-Buzon** [comment]
OMG yes pleasse!

**Comment by steveniwd** [comment]
Yes! Yes! It drives me crazy that sometimes I have to create a reversed copy of my content to display just for tablets

**Comment by codente** [comment]
We will look at this for 2.7 or 2.8.  Hopefully 2.7 though :)

**Comment by zackpyle** [comment]
@codente This should be moved to In Progress

https://www.wpbeaverbuilder.com/change-logs/#:~:text=Add%20option%20to%20reverse%20columns%20order%20on%20Medium%20breakpoint
