### ISSUE TITLE
Responsive Link Padding in Menu module

### ISSUE THREAD

**Issue by A-Buzon** [beaverbuilder/feature-requests#243]
Menu module doesn't allow for responsive Link Padding. You might want 20px on either side of menu links on desktop, but obviously on tablet, that's not going to work. What's worse is a Hamburger with a border/background with 
I'm surprised Link Padding doesn't have responsive settings.

Responsive Link Padding settings for each of the 3 breakpoints in the Menu module.

Alternatives: You either have to create separate menu modules to display for each breakpoint or you have to know how to write your own css.  Or deal with a menu that breaks into two lines on tablets.
![Screenshot 2022-04-28 133428](https://user-images.githubusercontent.com/34704467/165813377-d0f2e62f-45e3-4c55-9889-87158cf50b01.jpg)

**Comment by codente** [comment]
Hmm yeah that seems like an oversight. I'll see if we can get this into 2.6, if not before!

**Comment by A-Buzon** [comment]
Hello, I know you said this was an oversight and thought it could/would be updated soon, or at least by 2.6.  Any update? It's super annoying.  Thank you!

**Comment by codente** [comment]
Not yet - it was delayed so we could handle an issue that came up.  That padding also controls the toggle icon padding so we have sort that out to finish it up.

**Comment by A-Buzon** [comment]
Hello again! Love y'all and appreciate all your hard work!  Compliment sandwich...  still disappointed that menu padding is _**still**_ not responsive!  Again, love the additions, but fixing the existing should take priority! 
`@/*fastline*/media (min-fix:this) { 
.fl-menu.please { 
priority: 1;
love: 100%;
}}`

**Comment by codente** [comment]
Hi @A-Buzon the hold up with this is that toggle icon padding is also controlled from link padding so it was put on hold to look into the best way to handle that.  So we've worked to separate these two controls but still have to protect backwards compatibility.  I would expect that we could get this into 2.8 (which is in pre-release now).

**Comment by A-Buzon** [comment]
@codente for sure!  That was the primary reason for my request and why it's so absurd and obnoxious that there's no control over it.  
I will keep my fingers crossed that it gets taken off hold!  Thank you - I really appreciate it!!

**Comment by codente** [comment]
This went into 2.8
