### ISSUE TITLE
Add Label field content to Module title

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#249]
I would love it if the label field was appended to the module title so when I open a module, I can see the module type, and then label for it without having to go to the advanced tab to see the label

![Screen Shot 2022-06-06 at 10 10 56](https://user-images.githubusercontent.com/19413506/172189761-4a3e6b31-6905-4316-b490-ef79ef5c7386.jpg)

**Comment by codente** [comment]
This is in 2.6 beta.2

**Comment by codente** [comment]
In 2.6 :)
