### ISSUE TITLE
Improve instructions on "Beaver Builder has detected a plugin conflict..." pop-up

### ISSUE THREAD

**Issue by ksousa** [beaverbuilder/feature-requests#253]
I feel as though the instruction on the "Beaver Builder has detected a plugin conlfict..." pop-up could be clearer.

Following is a link to a suggestion I have (I'm not a wordsmith though) of how this could be restructured:
https://drive.google.com/file/d/1ZuOD-mmnRfoeHbFcDy1LxYf-XXbm-aYm/view?usp=sharing

**Comment by codente** [comment]
This is in 2.6 beta 2, out today!

**Comment by codente** [comment]
Now Live in 2.6.  Thanks for the suggestion!
