### ISSUE TITLE
Assistant Pro: Add plain text and shortcode to Code Snippets

### ISSUE THREAD

**Issue by Guenni1975** [beaverbuilder/feature-requests#259]
I have a suggestion for the "Add Code" section in Assistant Pro! 

When I create a new code, I have, under Extensions, the following selection of programming languages:
html, css, js, php 

It would be great if there was also an item "Text" and an item "Shortcodes" or similar, where you can enter things that do not explicitly belong to one of the above programming languages. 

Background is, that I use among others plugins, which generate different shortcodes, which are sometimes a bit more extensive. This would be great to have in the library.

Also I like to use text snippets, quasi building blocks, which I would like to save there.

*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by codente** [comment]
Thanks for this request.  We'll look into this.  Seems useful :)

**Comment by codente** [comment]
We did push out a plain text option and JSON option for code snippets!
