### ISSUE TITLE
Responsive Settings Icon: toggle back

### ISSUE THREAD

**Issue by studioavanti** [beaverbuilder/feature-requests#261]
Hi, 

When setting element's values responsively in BB UI, we have to click the responsive icon to jump to the next breakpoint and set specific values for each breakpoint: 
https://docs.wpbeaverbuilder.com/beaver-builder/layouts/responsive-design/responsive-settings-icon/

This toggle only works forward and in some situation, when you need to toggle back to the previous breakpoint, you have to click 2 or 3 times (BB 2.6 has 4 breakpoints) to reach the "previous" breakpoint, which also triggers 2 or 3 useless screen refresh.

Could you please consider adding a keyboard shortcut to toggle back instead of forth: the classic Shift-Click for instance?

Thanks for your interest.

![Capture d’écran 2022-07-16 à 17 28 12](https://user-images.githubusercontent.com/8690161/179361399-e73a8867-000a-46f0-8d9c-46d5a2793041.jpg)

**Comment by codente** [comment]
We are introducing a new keyboard shortcut in 2.8.1 to toggle in reverse order :)
