### ISSUE TITLE
Filter to hide/disable the BETA FEEDBACK button for white labeling.

### ISSUE THREAD

**Issue by gbissland** [beaverbuilder/feature-requests#263]
It doesn’t need to be a new admin toggle, but we’d love a filter to be able to remove the huge BETA FEEDBACK  button from client sites.

It is confusing for clients if BB is being white labelled, so maybe it could be tied to the Agency Plan or auto hidden if White Labeling is turned on?

I get it is good to get feedback. We generally upgrade client sites onto Beta 2+ and it usually increases our support tickets and client confusion if we don't hide it, which we currently have to remember to do via css.

**Comment by Pross** [comment]
There is a filter already `fl_builder_ui_bar_buttons` and the feedback buttons were added in 2019, you can use that filter to add/remove buttons.

**Comment by gbissland** [comment]
@Pross  If it is not possible to remove or hide the 'beta feedback' button for White Label or just Agency customers is it possible to use the 'Contact Support url' from the Help Button settings as the button destination instead of the BB website?

![Screenshot 2022-08-26 at 08 51 19@2x](https://user-images.githubusercontent.com/5170216/186767143-a4e0040e-9439-4c01-8042-b53126e41116.jpg)
