### ISSUE TITLE
Add page structure view. 

### ISSUE THREAD

**Issue by iamandrewpeters** [beaverbuilder/feature-requests#27]
**Is your feature request related to a problem? Please describe.**
The longer pages get the harder it is to get a birds eye view of the structure of the page. 

**Describe the solution you'd like**
Window or modal to view the pages overall layout and structure. Ability to name rows/columns to organize better. 

**Describe alternatives you've considered**

**Additional context**

**Comment by codente** [comment]
Duplicate of #1
