### ISSUE TITLE
Make Beaver Themer compatible with Buddyboss theme

### ISSUE THREAD

**Issue by jjbbrr** [beaverbuilder/feature-requests#272]
Currently Beaver Builder is compatible, but not Beaver Themer, so we can only edit page content. 

This is the page on their site where they advise current compatibility
https://www.buddyboss.com/integrations/beaver-builder/

Would be great to extend this to headers and footers as well.

**Comment by Pross** [comment]
BuddyBoss will need to add support, see https://docs.wpbeaverbuilder.com/beaver-themer/developer/add-header-footer-and-parts-support-to-your-theme-themer for examples
