### ISSUE TITLE
Modules and columns width CSS parameters has decimals calculation incompatibility according server LOCALE

### ISSUE THREAD

**Issue by caiobleggi** [beaverbuilder/feature-requests#276]
**Is your feature request related to a problem? Please describe.**
Modules that need to calculate widths or heights based on settings values, like Post Grid Module when set to Columns Layout, has an CSS incompatibility issue with different LOCALES, for example pt_BR (Brazilian Portuguese) uses comma as a decimal separator while English default LOCALE uses the dot. This affect the generated CSS directily because there`s no treatment on the calculations making the columns to break as they end up with an invalid width value.

**Describe the solution you'd like**
Adjust calculations on bb-plugin/module/MODULE-NAME/includes/frontend.php and similiars files including [number_format](https://www.php.net/manual/pt_BR/function.number-format.php) php function with decimal parameter properly set to the dot avoiding CSS breaks in any LOCALE or different enviroment cases.

**Describe alternatives you've considered**
Meanwhile I had to force the linux numeric LOCALE to English for compatibility and non-breaking CSS files:

`sudo update-locale LC_NUMERIC="en_GB.UTF-8" `

**Additional context**
See the result of a column calculation in a pt_BR.UTF-8 LOCALE server: 
![image](https://user-images.githubusercontent.com/1514201/193595268-87414785-7d1e-45e3-b471-d871fe151ada.png)

**Comment by Pross** [comment]
In the future please report bugs to the help desk, this github is for feature request tracking.

I tried to replicate your issue by doing the following:

Created a new WP VPS install and set machine locales to pt_PT
```
root@pt-testing-delete:/var/www/html# locale
LANG=pt_PT.UTF-8
LANGUAGE=
LC_CTYPE="pt_PT.UTF-8"
LC_NUMERIC=pt_PT.UTF-8
LC_TIME="pt_PT.UTF-8"
LC_COLLATE="pt_PT.UTF-8"
LC_MONETARY="pt_PT.UTF-8"
LC_MESSAGES="pt_PT.UTF-8"
LC_PAPER="pt_PT.UTF-8"
LC_NAME="pt_PT.UTF-8"
LC_ADDRESS="pt_PT.UTF-8"
LC_TELEPHONE="pt_PT.UTF-8"
LC_MEASUREMENT="pt_PT.UTF-8"
LC_IDENTIFICATION="pt_PT.UTF-8"
LC_ALL=
```
Set PHP locale in php.ini
<img width="859" alt="Screenshot 2022-10-03 at 16 22 25" src="https://user-images.githubusercontent.com/265860/193615164-a20570eb-d02e-41a3-99bf-118c0a7cb8e3.png">
Also WP is set to pt_PT in general settings.

Now when I add a post grid to the page it is still 33.3333333%
<img width="317" alt="Screenshot 2022-10-03 at 16 23 40" src="https://user-images.githubusercontent.com/265860/193615433-59bc6c7d-b434-43de-8d6e-6269f230e7fd.png">

If you have done something different than this please let us know in a support ticket but it does sound like its a config issue.
