### ISSUE TITLE
Add categories plus a current list of saved modules, rows, etc. while saving

### ISSUE THREAD

**Issue by jodzeee** [beaverbuilder/feature-requests#30]
**Is your feature request related to a problem? Please describe.**
When I save a row, module, etc., I just get the option to add a name and choose whether or not it's global. I try to keep them categorized as well as use a naming convention to keep them organized, but don't always remember what it is. Sometimes I may have already even saved that one, but don't remember and it results in duplicates and an organizational nightmare.

**Describe the solution you'd like**
I would like the option to choose a category when saving a module, row, etc. as well as to be able to see a current list of what's already been saved while saving a new one. Having the ability to add notes to each, would also be helpful!

**Describe alternatives you've considered**
I currently open a new tab showing what I already have saved.

**Additional context**
Maybe this should be two requests, but they're both related to saving a module, row, etc., I lumped them together.

**Comment by Dannyholt** [comment]
@jodzeee 

Do you mean something like this?

![](https://p199.p4.n0.cdn.getcloudapp.com/items/mXuyoA6e/Screenshot%202020-08-02%20at%2018.45.01.png?v=61d9e6390bce7c453e319a871b3cf0e9)

**Comment by jodzeee** [comment]
Yes! Does this exist somewhere?

**Comment by Dannyholt** [comment]
No, I quickly added those fields using Chrome dev tools as I wasn't entirely sure if this is what you meant. :D

**Comment by codente** [comment]
We are working on this feature, or most of it.  If all goes well, will be in the next 2.8 beta, this week!
