### ISSUE TITLE
Update Font Awesome Version

### ISSUE THREAD

**Issue by aidenguinnip** [beaverbuilder/feature-requests#303]
The Font Awesome font I'm BB should be updated to the latest from Font Awesome. And do so on a regular basis, as it updates frequently.

For instance, this icon is not available in BB: https://fontawesome.com/icons/glass-water?s=regular&f=classic

**Comment by codente** [comment]
That's a FA6 icon.  For compatibility with FontAwesome 6, you'll want to install the Official FontAwesome plugin.
