### ISSUE TITLE
Make stacking order field responsive

### ISSUE THREAD

**Issue by dmvdev01** [beaverbuilder/feature-requests#321]
Problem is that if I want a stacking order on tablet portrait, it's not possible because it only works on mobile. '

<img src="https://i2.paste.pics/9b10ba57e775396dde8c547b7bfcf55b.png" width="720" height="132" alt="Screenshot">

**Comment by codente** [comment]
Stacking on tablet/medium breakpoint is a feature of 2.7 :)
