### ISSUE TITLE
Add flexbox controls to rows and columns

### ISSUE THREAD

**Issue by dmvdev01** [beaverbuilder/feature-requests#323]
We need advanced flexbox controls for rows and columns so we have way more control over the layout.
Another thing is SEO. GTmetrix and other tools are complaining that I have way to many nested divs on my BB sites. If we could just add a simple row with flexbox controls this would eliminate the need for a lot of divs for the columns etc.

<img src="https://i2.paste.pics/804caf6751c2dcac7d97eff674358473.png" width="584" height="1462" alt="Screenshot">

<img src="https://i2.paste.pics/2a8913798b3342d060bf3578db3f4081.png" width="560" height="400" alt="Screenshot">

**Comment by zackpyle** [comment]
@codente Should this be marked as In Progress?

**Comment by codente** [comment]
Closing this as we we will not be adding this to current rows/columns.  Instead we're working on a new container type with flex/grid support.  That will be out in a pre-release very soon (hopefully this month)
