### ISSUE TITLE
Post loop builder

### ISSUE THREAD

**Issue by dmvdev01** [beaverbuilder/feature-requests#325]
I'd like to create a saved row that I would style as a single post item that becomes part of a new module called post loop builder. This module loads the saved row and repeats it for all the posts. In the saved row itself I connect all fields like the image, post titel, button url etc with the Beaver Themer field connector. 

The post loop module shows all these saved rows / saved blocks in a CSS grid or slider or whatever and loads the dynamic values for each block like post title, featured image etc.
We also need a super advanced query with it to filter the (custom) posts.

You don't have to figure out how to create this because it has already been done. If you would just create something like this video below, that would be really awesome!

https://www.youtube.com/watch?v=EM6mfgQQHlA
Other builders like Elementor have this feature too.
It's nice that you can use the BB modules to create a single post item.

PS: The saved row could also be a template if that is more convenient to do, but I hope you get the idea.

**Comment by innovauno** [comment]
YES, definitely. Now I do it via writing custom html in the Posts module with shortcode connections. But a proper loop builder would be extremly valuable and easing dev works. Plus, like you said, most of the logic is already there 👍

**Comment by codente** [comment]
A visual loop builder is in our radar.  It's already been requested here though so I'm going to close this one so we only have one issue.

https://github.com/beaverbuilder/feature-requests/issues/291
