### ISSUE TITLE
export the date, heading and description from all items in a module as a text file

### ISSUE THREAD

**Issue by sulines** [beaverbuilder/feature-requests#326]
we have invested a lot of time populating BB modules with our research. we need a way to export the date, heading and description fields from all items in a module as a text file.

we know how to use Export/Import under Advanced settings but that embeds those fields in a ton of code making it impossible to create easily editable text.

**Comment by zackpyle** [comment]
What about just using a common page scraping application?

**Comment by sulines** [comment]
A few reasons.  First, the particular module is a horizontal timeline that only displays three cards at a time.  Users need to click an arrow to get to the next three.  We have 200 cards in our timelines.  Second, this timeline module prevents text selection.  Third, we need this functionality as part of the standard modules so it cleanly generates the data as text, just like the current Export, but without all the html code surrounding the data.

**Comment by sulines** [comment]
Thanks for the offer zackpyle.  We only use fully supported BB code.  I hope they read this, take you up on your offer, and provide it as supported code.

**Comment by zackpyle** [comment]
They won't. I can almost guarantee you that. But all you need is some js to grab the info and output it. If you don't want my help though, that's up to you

**Comment by sulines** [comment]
We appreciate your offer and no disrespect intended.  We are sure you are a talented js coder, but we are not so we could not evaluate the code before running it on our site.  That is why we only use fully supported BB code.

**Comment by zackpyle** [comment]
Ok. But if you checked the BB facebook group, you would see that I help people all the time 🤷🏼‍♂️ Let me know if you change your mind.

FWIW, the code wouldn't be running on your website. It would only be ran in your browser. It would have 0 effect on your actual site.

**Comment by sulines** [comment]
Zack,  You said this will take you 5 minutes.  Can you still do this?

**Comment by zackpyle** [comment]
Sure. Depends on what the request is of course 👍🏻

**Comment by sulines** [comment]
it's what we discussed in this post.  we use [Ultimate Addons for Beaver Builder Advanced Timeline module](https://www.ultimatebeaver.com/modules/advanced-timeline/).

**Comment by zackpyle** [comment]
Send me an email with the link and a summary of what you want pulled 👍🏻

zack@pyledigital.com

**Comment by zackpyle** [comment]
Done. Sent the export back 👍🏻

**Comment by sulines** [comment]
Excellent!  Thank you Zack.
