### ISSUE TITLE
ACF: Test Values based on other field types

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#33]
I want to be able to test a value with other ACF field types. An example would be that I wanted to conditionally display content in a post module depending on the value of an ACF Select field.

**Describe alternatives you've considered**
Currently, my workaround for the example above was to add an additional Radio field (since Themer can check values of a radio button) on the backend for the user to select the field type they want to display, and then use ACF to conditionally show the appropriate field type below depending on their answer.

**Comment by Pross** [comment]
Technically you _can_ check for the output of a select field if it is set to return text. If multiple items are selected it will return a comma-separated list or ul/li if text is not set in the field options.

**Comment by zackpyle** [comment]
@Pross It was a single select field... That's what I would have assumed should have happened (contrary to the help docs specifying field types), but whatever I tried, it always came out "true" even though it was false.

Maybe I'll submit a ticket then?

**Comment by zackpyle** [comment]
@Pross Actually, I would have to re-create it on dev site as I already did my workaround...

**Comment by Pross** [comment]
No need. Its documented here anyway. The select acf _should_ output the selected content, in the code there is no true/false if you are testing using wpbb-if you are testing against TEXT not boolean do you have an example?

**Comment by Pross** [comment]
If its not set to _text_ then the field will always output the field contents wrapped in `<li></li>` which is probably why its always true. As a test just output the shortcode itself and see what it outputs, that'll show you what you are testing against

**Comment by zackpyle** [comment]
**ACF Setup:**
Select Field 1 (fi_std_manual) -> Option 1, Option 2, Option 3, Manual Input
Text Field 1 (and conditionally displayed in ACF if Select field = Manual Input) -> "This is a manual input."

**BB custom layout:**
[wpbb-if post:acf type='text' name='fi_std_manual' exp='notequals' value='Manual Input']
    [shortcode to display Select Field 1]
[wpbb-else]
    [shortcode for Text Field 1]
[/wpbb-if]

**Result:**
Always shows "Content" even if Select field is set to Manual Input

**Comment by Pross** [comment]
is this a typo?
`[wpbb-if post:acf type='text' name='fi_std_manual' exp='notequals' value='Manual Input']`

**Comment by zackpyle** [comment]
Not that I can tell. What are you seeing that is wrong?

**Comment by Pross** [comment]
well you said it was a select field but you have type set to text.

What does `[wpbb-if post:acf type='text' name='fi_std_manual']` and `[wpbb-if post:acf type='select' name='fi_std_manual'` output

**Comment by zackpyle** [comment]
They both output the same thing

**Comment by codente** [comment]
In Themer 1.4
