### ISSUE TITLE
Open Media Library Button in Toolbar

### ISSUE THREAD

**Issue by HowdyMcGee** [beaverbuilder/feature-requests#333]
**Is your feature request related to a problem? Please describe.**
I've run into multiple occasions where a client will want to link a PDF to a button module or a similar module where the module doesn't give them direct access to the Media Library. Walking them through either exiting Beaver Builder or adding a new Text Editor Module where they get access to the Media Library is cumbersome.

**Describe the solution you'd like**
I would like to see a Media Library Icon somewhere in the Beaver Builder Toolbar where the client can open up the Media Library directly without having to add a new module or leave the Beaver Builder screen.

**Describe alternatives you've considered**
The alternatives involve hooks and development, which always come back to either opening the Media Library or linking to the Media Libray in the admin panel.

**Comment by codente** [comment]
@HowdyMcGee can you explain more what problem you're trying to solve? You can with the link field, select PDFs that are already uploaded to the media library in a link field (Demo here: https://share.getcloudapp.com/Z4uGGkyA)

**Comment by HowdyMcGee** [comment]
@codente This assumes that the file has already been uploaded elsewhere on the website. If this is a new file that the client is looking to link - there's no easy way to access the media library while the builder is open. The alternatives to add the new file are non-intuitive. A link opening the media modal to allow access seems like the most user-friendly solution.

**Comment by codente** [comment]
@HowdyMcGee Thanks for the details.   Would us adding a link to Tools > WordPress Admin to the media library that opened in a new tab like the others help?

**Comment by codente** [comment]
Check out 2.8 beta.2 when you get a chance.  That should be out sometime today :)

**Comment by HowdyMcGee** [comment]
Love it! This is going to make it so much easier to explain to clients when they need to link their PDF files. Thank you builder team for listening!

**Comment by codente** [comment]
Glad to hear that @HowdyMcGee!

**Comment by gbissland** [comment]
PowerPack included a File Download module which does exactly this.
It is essentially just their smart button module with a File Upload option, which opens the Media Library to upload or attach a file. Perfect!
I'm not sure why this 'feature' cannot be included in all the regular BB button modules. It is super useful for speed and keeping client in BB, not  having to go out upload the PDF, get the url etc as stated.

![Screenshot 2023-11-21 at 11 52 58](https://github.com/beaverbuilder/feature-requests/assets/5170216/075c1d44-9433-4f59-9872-097277b8835e)

**Comment by codente** [comment]
That's what this feature aims to do - keep users inside the UI so they don't have to exit to get to the media library.

**Comment by codente** [comment]
This was added in 2.8 so I'm closing!
