### ISSUE TITLE
Repeater for Row/Column Background Gradient Colors

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#336]
**Is your feature request related to a problem? Please describe.**
There are only two color pickers for background gradients. There isn't a way in the BB UI to make a more complex gradient

![Screenshot 2023-08-16 at 09 10 32](https://github.com/beaverbuilder/feature-requests/assets/19413506/09cbe665-7d24-40a3-a305-c4dcc35442ba)

**Describe the solution you'd like**
Please add a repeater (+) icon for the user to add more color pickers to add to their gradient as well as draggable handles to reorder the colors.

**Describe alternatives you've considered**
The only current alternative is to write the BG gradient in CSS

**Comment by LydiaKitts** [comment]
I would love this so much! I have to create custom classes right now.

**Comment by zackpyle** [comment]
Closing this out as it is solved in the upcoming v2.9 using the new multiple background feature
