### ISSUE TITLE
Ability to Create Folders for Saved Modules

### ISSUE THREAD

**Issue by pixelloop** [beaverbuilder/feature-requests#350]
**Is your feature request related to a problem? Please describe.**
I want to be able to create folders for my saved modules and rows to better organize them. 

**Describe the solution you'd like**
An option that allows you to add to or create a folder when clicking "save as" on a module or row. 

**Describe alternatives you've considered**
I don't think there is an alternative.

**Comment by pixelloop** [comment]
I found the categories feature and that works well enough.

**Comment by jodzeee** [comment]
@pixelloop - please upvote my similar request from 2020 😊 
https://github.com/beaverbuilder/feature-requests/issues/30

**Comment by pixelloop** [comment]
> @pixelloop - please upvote my similar request from 2020 😊 #30

I have upvoted it. That would definitely be easier than having to categorize in the dashboard after the fact.
