### ISSUE TITLE
Add an Icon or Contextual Right Click Menu when accessing a Modules Parent Container such as Column

### ISSUE THREAD

**Issue by neilgee** [beaverbuilder/feature-requests#354]
In the new BB plugin 2.8, when accessing a Parent Container via a Modules parent hierarchy tree, it also opens the Parent Containers setting box.

You  may just want a simple Duplicate or Removal of that Parent Container but the new version of BB opens up the Parent Setting Box which you will want to dismiss to see the whole layout - you can duplicate containers via the Outline Panel but this may also obscure the view and you have to close it.

So the new way is less convenient and takes more steps. How about 2 alternatives:

### **Contextual Menu**

What would be better and faster with less screen clutter is a _**Contextual Right Click Menu**_ on the **Parent Container** such as Column,  that has the same contextual menu as the Outline Panel:

- Open Settings
- Duplicate
- Remove

![parent-contextual-menu](https://github.com/beaverbuilder/feature-requests/assets/2056045/03abf856-3856-45fe-9e81-a86543d7ebff)

### **Icon Menu** 

Including

- Open Settings
- Duplicate
- Remove

This repeats for each parent in the hierarchy.

![bb28-option-menu-icon](https://github.com/beaverbuilder/feature-requests/assets/2056045/6133af73-a060-4803-b59d-f7e29ca5bd8e)

**Comment by studioavanti** [comment]
Related to this issue, how do we delete a Box module or a column populated by modules when using a touch device?
I can't find a way to do this anymore with BB 2.8 new UI, either in the layout nor in the layout panel.

@neilgee's suggestion for a contextual menu seems to be a solution.
Another one would be to have Duplicate and Remove in the item Settings panel.

**Comment by neilgee** [comment]
BB folk have implemented this in 2.8.0.2  - great addition
