### ISSUE TITLE
Split Text Modules

### ISSUE THREAD

**Issue by gsgwebmaster** [beaverbuilder/feature-requests#355]
When first activating Beaver Builder on pages that were not originally built with Beaver Builder, the entire page is a text module. It can be huge. Currently, if I want to insert a new row or module somewhere within this page (for example a global module), I either need to duplicate the huge text module and carefully delete half from each copy of the module, or copy and past large amounts of text into a new module and delete the copied text from the original module.

Would be nice to have an option to split a text module at the desired location to allow insertion of a new row.

The inspiration for this comes from maintaining our blog, where we've included an author bio within the page body for years prior to using Beaver Builder. Sometimes we need to update the author bio, causing a bunch of work to update hundreds of blog posts to fix it. So we've been manually going through every blog posts and using the duplicate-insert method described above to change the author bio to a global module. Since we're touching hundreds of old posts, it makes sense to make the change to a global module instead of just updating the author bio details. But it reminded me that the duplicate-insert method is something I find myself doing regularly with Beaver Builder, where a split-insert function would be better.

**Comment by codente** [comment]
This is something that just isn't feasible, I'm afraid.
