### ISSUE TITLE
Green dot for customized CSS/JS sections in BB item panel

### ISSUE THREAD

**Issue by studioavanti** [beaverbuilder/feature-requests#360]
Please BB devs, add a **green dot to the CSS/JS sections** in the BB item panel when they're customized, in order to help users to quickly spot custom code in these areas!

Just like this already exists in BB Tools Layout/Global CSS/JS sections… and despite it's much too discreet, increasing the green dot size would really help as well.

![CleanShot 2024-04-06 at 00 44 49](https://github.com/beaverbuilder/feature-requests/assets/8690161/590e509a-13f4-4b9c-b8ed-44cb793673a3)
![CleanShot 2024-04-06 at 00 46 47](https://github.com/beaverbuilder/feature-requests/assets/8690161/4e958186-f003-4cec-86bb-3f9f4439a956)

**Comment by codente** [comment]
In progress!

**Comment by codente** [comment]
This should be in 2.8.2, due out later this month!

**Comment by studioavanti** [comment]
Great and useful, thank you.

**Comment by zackpyle** [comment]
Should be marked as Closed?
