### ISSUE TITLE
Ability to add custom data attributes

### ISSUE THREAD

**Issue by andrewdodson14** [beaverbuilder/feature-requests#373]
I'd love to have the ability to add custom data attributes to modules, columns, rows just like IDs and Classes on the Advanced tab, with the exception it should be a "repeater" or Form field instead of just one field like ID and Class. This would come in handy for integrating BB with 3rd party JS libraries like Rellax as a specific use case.

Each module, column, row would have a Form field on the Advanced tab below the ID and Class fields. You'd be able to add multiple attributes, each with label and value fields. For example, data-rellax-speed (label) and -2 (value). 

I've attempted adding this myself, but there seems to be issues with adding a Form field vs. other regular fields.

**Comment by Pross** [comment]
Duplicate #255
Duplicate #196 ( which has multiple solutions )
