### ISSUE TITLE
node custom css compiler variables

### ISSUE THREAD

**Issue by badabingbreda** [beaverbuilder/feature-requests#378]
**Is your feature request related to a problem? Please describe.**
Adding global styles/colors in the global styles panel is a tedious process. It also has to be done per color on a site. I'd like a way to add such colors in another manner, using a filter hook.

**Describe the solution you'd like**
I see an opportunity to make adding custom CSS more powerful. I noticed that the custom CSS allows you to use SCSS, since it's being filtered using the `filter_layout_css` callback in file called `class-fl-builder-node-code-settings.php`. I think it wouldn't hurt to add a filter like - for instance - `fl_builder_node_code_css_variables` to add variables to the compiler:

`$compiler->addVariables( apply_filters( 'fl_builder_node_code_css_variables' , [] , $node_id , $node ) );`

This way, based on $node_id or properties that can be derived from $node (like ->name) variables like colors, widths, breakpoints etcetera can be added to generate CSS that use these variables on a per Module Type basis.

**Describe alternatives you've considered**
I've tried to hook into the global styles array using callbacks. That didn't work, really.

**Additional context**

**Comment by Pross** [comment]
Nice suggestion.

Ended up with this as the change

```
					$compiler = new ScssPhp\ScssPhp\Compiler();
					/**
					 * Allow an array of SCSS variables
					 * @see fl_builder_node_code_css_variables
					 * @since 2.9
					 */
					$variables = apply_filters( 'fl_builder_node_code_css_variables', [], $node_id, $node );
					if ( ! empty( $variables ) ) {
						foreach ( $variables as $k => $variable ) {
							$variables[ $k ] = ScssPhp\ScssPhp\ValueConverter::parseValue( $variable );
						}
						$compiler->addVariables( $variables );
					}
```

You have to use ScssPhp\ScssPhp\ValueConverter::parseValue() otherwise the library throws a PHP warning

**Comment by badabingbreda** [comment]
Excellent, thanks for the quick response. And great catch on the parseValue method. I've had to use that in my custom plugin as well so don't know why I forgot to mention that.
