### ISSUE TITLE
Add a "contains" operator for wpbb-if

### ISSUE THREAD

**Issue by deargeek** [beaverbuilder/feature-requests#46]
To be able to test for the presence of text within a field.

For example, a checkbox field for a hotel room post type gives the result...

tea,fridge,king,wifi

...when queried with [wpbb post:acf type='checkbox' name='icons' checkbox_format='text']

I would like to be able to do something like...

```
[wpbb-if post:acf type='checkbox' name='icons' checkbox_format='text' exp='contains' value='king']
  display icon for kingsize bed
[/wpbb-if]
```

**Comment by codente** [comment]
Now Live in Themer 1.4.1
