### ISSUE TITLE
Ability to set global color palette

### ISSUE THREAD

**Issue by codente** [beaverbuilder/feature-requests#6]

**Comment by kbysfm** [comment]
It would be amazing to include shortcodes generated from color label #9  

Imagine then using color shortcodes in the tools css/js menu (i know already possible)

example

`.background-primary { background-color: [wpbb-primary-color]`

**Comment by imagineowl** [comment]
Yes, even if we were able to "edit" the saved colors, and have it update where ever it was used before.

Also, the "saved" or "global" colors would be nice to have in the customizer, so our clients can easily change their color combos.

**Comment by Clark-AG** [comment]
Yes I would like to edit a saved color and see it change throughout the site wherever that color was used.

I once built a different site using a theme that had this feature. It was amazing!

**Comment by codente** [comment]
Make sure you give the initial post a thumbs up if you want your vote to be counted.

**Comment by EnterpriseBranding** [comment]
Forgive me if I am wrong, but I think it would make sense to post this here and not on a new thread, as this question is a temporary solution to this feature request.

I've had this request for quite awhile now:

Is there a way to allow entries into the color picker like `var(--main_background)`?

I've tried enter these manually into the color picker, but of course it fail validation.

But if this can be done, and maybe added along with this request, it would allow more control and integration with other plugins and theme colors.

**Comment by zackpyle** [comment]
@codente I think another implementation of this could be that the Color Presets that BB saves could be output to the :root as css variables. Then you could set your colors in BB Color Presets but those colors could be accessible via CSS anywhere!

**Comment by Pross** [comment]
Adding var() to the color field currently isn't possible without modifying code. However...

@zackpyle you can use this to add the colours to the root..

```
add_action( 'wp_head', function() {
	$presets = (array) FLBuilderModel::get_color_presets();
	$style   = '';
	foreach( $presets as $k => $colour ) {
		$style .= sprintf( '--bb-preset-%s: %s;', $k, $colour);
	}

	if ( '' !== $style ) {
		printf( '<style>:root{%s}</style>', $style );
	}
});
```

And if you apply this patch you'll be able to use var() in an acf text field for the colour.

```
From 6eead288e23c52fe6c08ed6d01cef4d918359b74 Mon Sep 17 00:00:00 2001
From: Simon Prosser <pross@pross.org.uk>
Date: Wed, 2 Jun 2021 20:01:51 +0100
Subject: [PATCH] Allow var in hex_or_rgb or rgb function

This will allow people to at least use custom fields for colour vars for now.
---
 classes/class-fl-builder-color.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/classes/class-fl-builder-color.php b/classes/class-fl-builder-color.php
index 02f6cc5f8..9765ad59c 100644
--- a/classes/class-fl-builder-color.php
+++ b/classes/class-fl-builder-color.php
@@ -54,7 +54,7 @@ static public function hex_to_rgb( $hex ) {
 	 * @return string
 	 */
 	static public function hex_or_rgb( $color ) {
-		if ( ! empty( $color ) && ! stristr( $color, 'rgb' ) && ! stristr( $color, '#' ) ) {
+		if ( ! empty( $color ) && ! stristr( $color, 'rgb' ) && ! stristr( $color, '#' ) && ! stristr( $color, 'var' ) ) {
 			$color = '#' . $color;
 		}
```

**Comment by Bobolinos** [comment]
@Pross, problem with your code is that we cannot change an existing color to a new color, thats the idea of global colors.

**Comment by zackpyle** [comment]
Should this be set as In Progress?

**Comment by codente** [comment]
This is in 2.8 which is now live so closing!
