### ISSUE TITLE
Add Search Input for Saved templates

### ISSUE THREAD

**Issue by AchalJ** [beaverbuilder/feature-requests#69]
Consider adding search input for saved templates panel just like one on modules panel.
It's not convenient to find a particular saved row/module where you have a long list of saved templates.

![image](https://user-images.githubusercontent.com/12668839/96895267-e0e40300-14a9-11eb-9979-790f5c311822.png)

![image](https://user-images.githubusercontent.com/12668839/96895785-6798e000-14aa-11eb-975e-1379d4e3f8e8.png)

**Comment by studioavanti** [comment]
Yes, i also think it would be a useful feature, being able to search though templates and/or saved items (rows, columns, modules). 
It's an important waste of time to locate saved items by scrolling a long list.

**Comment by codente** [comment]
Planned for 2.6!

**Comment by codente** [comment]
In 2.6!
