### ISSUE TITLE
UI brightness usability

### ISSUE THREAD

**Issue by sulines** [beaverbuilder/feature-requests#84]
I accidentally learned that hitting the letter "o" toggles between white and black menus with no warning or hint how they changed.  That forced me to search throughout the plugin settings until I realized there are other settings in the BB interface and finally resorted to trying the cryptic "change ui brightness."

I love BB but this is the worst implemented option that someone can trip over and start worrying a virus has taken over BB.

Cindy2477 posted the same question in your community forum back on Apr 15 and never received a reply.  

**Describe the solution you'd like**

clear and unambiguous notification that the letter "o" was pressed and that caused the menu color to change.  

change the cryptic name from "change ui brightness" to toggle menu color black or white

thx

**Comment by Dannyholt** [comment]
The **Change UI Brightness** best describes what this option does for me. We could maybe change this to Light mode/Dark mode but they may confuse some users so I do believe what we have at the moment is the best description.

The "o" is a keyboard shortcut and is very clear in my opinion already. You can see this from the Tools menu.

<img src="https://p74.tr4.n0.cdn.getcloudapp.com/items/bLu0DGGe/Screenshot%202020-11-25%20at%2018.17.29.png" width="200">

If you don't like this shortcut, you can remove it following the instructions below.

https://docs.wpbeaverbuilder.com/beaver-builder/developer/tutorials-guides/customize-keyboard-shortcuts/#remove-a-keyboard-shortcut

**Comment by sulines** [comment]
Hi Danny, you've helped us several times in the past.

change ui brightness in all other implementations, from phones to TVs, shows a - + and a graphic representation of the ui lightening to brightening from 0% to 100%.  

the problem is: i never needed or had any intention to know anything about this option.  i was working and accidentally hit the letter o and all the menus changed.  it was startling and caused me, and apparently Cindy2477, to wonder if we were hit by a virus.  Cindy2477 was so concerned she twice posted in your community forum and never received a reply.

clear and unambiguous notification that the letter "o" was pressed, causing all the menus to change color, and to press o again to revert back to white.  that should be easy to implement, right?

**Comment by Dannyholt** [comment]
> change ui brightness in all other implementations, from phones to TVs, shows a - + and a graphic representation of the ui lightening to brightening from 0% to 100%.

This isn't really an accurate comparison. As this doesn't changing the actual brightness i.e. 10%, 20% etc. It is switching the UI from light to dark or vice-versa, similar to iPhones. As I mentioned previously the labelling could be reworked to Light/Dark mode which I will bring up in our next meeting.

> the problem is: i never needed or had any intention to know anything about this option. i was working and accidentally hit the letter o and all the menus changed. it was startling and caused me, and apparently Cindy2477, to wonder if we were hit by a virus. Cindy2477 was so concerned she twice posted in your community forum and never received a reply.

The Beaver Builder community forum is run by the community and works similar to our community Slack and Facebook group, but hosted by us. Although our team are present in those communities it isn't an official support resource. If you need assistance from our team you will want to submit a ticket to our helpdesk using the form on our [support page](https://www.wpbeaverbuilder.com/beaver-builder-support/).

> clear and unambiguous notification that the letter "o" was pressed, causing all the menus to change color, and to press o again to revert back to white. that should be easy to implement, right?

We could add some graphical notification informing you the UI has switched, but I don't really see how a notification saying "UI has changed" when you can already see it. :) However, I'll keep this request open and show our team. :)

**Comment by sulines** [comment]
i accidentally hit the letter "o" and had no idea what caused the menus to change color.  the only way i figured it out was by spending way too much time worrying about a possible virus and searching through all of BB's settings and guessing that the cryptically name "change ui brightness" might have something to do with it, and then, after seeing it did change the menus back to white, only then did i notice that the shortcut was clicking "o" and presumed that's what caused my having to chase rabbits down several holes.  in this case some sort of notification could have saved me a lot of time and concern.

**Comment by gingersoulrecords** [comment]
Personal opinion here: I don't think there should be a keyboard shortcut for something you don't need to use regularly, especially something as 'easy to press' as a single key. You don't switch from dark, to light, to dark again during a work session, typically (at least I don't). 

Dark/Light mode should just be a switch in the settings dropdown.

**Comment by sulines** [comment]
agreed.

**Comment by Dannyholt** [comment]
> Personal opinion here: I don't think there should be a keyboard shortcut for something you don't need to use regularly, especially something as 'easy to press' as a single key. You don't switch from dark, to light, to dark again during a work session, typically (at least I don't).
> 
> Dark/Light mode should just be a switch in the settings dropdown.

I believe the idea is that you can quickly switch to dark mode when working at night so it is easier on the eyes. As I mentioned above, you can simply disable the shortcut for that option.

**Comment by gbissland** [comment]
FWIW I do switch during the day/night or depending on mood. I like the quick shortcut.

Dark modes are getting more common in apps, so I'm not sure it should freak too many people out, but maybe the wording around the shortcut could be improved instead of UI Brightness, maybe just 'UI - Light / Dark mode'

**Comment by gingersoulrecords** [comment]
A shortcut is ok, I'd just wire it so people aren't tripping over it. Single-key shortcuts are nice for things like responsive editing or saving, but without a notification ('dark mode enabled, press 'o' to revert') it can be jarring, especially to first-timers.

If you're not following an established convention (like Cmd-S to save), you should 'explain yourself' with extra information.

**Comment by sulines** [comment]
Thanks for today's update: 2.4.1.3 - 12/21/2020

Remove Dark Mode keyboard shortcut due to customer feedback (#929)

**Comment by codente** [comment]
Based on feedback, in 2.4.1.3 we removed the Keyboard Shortcut and as a result, closing this now.
