### ISSUE TITLE
Dark mode code highlighting

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#88]
When enabling dark mode in BB editor, code highlighting goes away

Please fix :)

**Comment by codente** [comment]
This is a known bug that we haven't been able to fix.

**Comment by gingersoulrecords** [comment]
Hey @codente! 

I detailed the fix in my request, with the line of code and location. 

DB

**Comment by zackpyle** [comment]
I can confirm that @gingersoulrecords is correct. Please take the extra 30 min to target the correct elements with this CSS instead of a blanket *:not(i) and that will solve this problem

`.fl-builder-ui-skin--dark .fl-lightbox *:not(i) {
    color: #a7b1bb !important;
}`

**Comment by codente** [comment]
Passed along the suggestions to the team.  Like I said, we tried to fix this before, multiple times and it created more issues.

**Comment by Dannyholt** [comment]
@zackpyle @gingersoulrecords 

This and #90 were closed because we consider this a bug not a feature request. ;)

**Comment by codente** [comment]
Fixed in BB 2.4.2 - out now! https://www.wpbeaverbuilder.com/change-logs/
