### ISSUE TITLE
Responsive Margins/Padding showing grayed out 0 instead of true number

### ISSUE THREAD

**Issue by zackpyle** [beaverbuilder/feature-requests#89]
**Is your feature request related to a problem? Please describe.**
When switching to responsive mode, padding/margins show 0 instead of the actual number. This is especially frustrating when you set a custom value in Desktop, and then it showing 0 on tablet/mobile

**Describe the solution you'd like**
Show the actual number for margin/padding in responsive mode

**Comment by codente** [comment]
This is actually a bug.  And one that we thought we fixed in 2.4 but I'm still seeing it so I filed a bug report.  

Bug reports still go through the normal channels so closing this.

**Comment by codente** [comment]
2.4.1.3 is out now which should resolve this!  If you are still having trouble after updating, please file a bug report via the support ticket form.  Thank you!
