### ISSUE TITLE
Assign color picker labels

### ISSUE THREAD

**Issue by codente** [beaverbuilder/feature-requests#9]
Ability to give labels to colors in color picker

**Comment by A-Buzon** [comment]
I need this so bad!  "2nd Accent Color" and "Main Hover Color" rather than "#ededed" and "#282828" would reallllly help, especially when turning it over to a client.

**Comment by Clark-AG** [comment]
Yes please. I've suggested this exact feature twice!

**Comment by 3001Web** [comment]
I would love to see this too, it is one of those silly little things that would speed up workflow

**Comment by codente** [comment]
Closing as we can't do this with our color picker but Global Colors now accomplishes this.

**Comment by A-Buzon** [comment]
@codente Yes, yes indeed it does!! WOOT!! WOOT!!
