### ISSUE TITLE
Ability to modify login URL

### ISSUE THREAD

**Issue by jasonpierson** [beaverbuilder/feature-requests#95]
**Is your feature request related to a problem? Please describe.**
At the bottom of each post is a login link. We have several sites that use the Beaver Builder theme. For these sites, we have a single sign-on(SSO) page on a separate server. Currently, this link is hardcoded on line 75 of /comments.php. We cannot change the link without changing the code in the theme.

**Describe the solution you'd like**
The standard way to get the login url in WP is to call the `wp_login_url()` function. If this were done here, we could hook into it via the `login_url` filter and change the login url without changing the theme code.

**Describe alternatives you've considered**
Changing the theme code. Which is bad.

**Additional context**
This is what the link I'm talking about looks like:
![Screen Shot 2021-01-15 at 1 49 36 PM](https://user-images.githubusercontent.com/5942405/104772201-abf9ec00-5738-11eb-8f6b-bc92572a920f.png)

**Comment by codente** [comment]
Hi Jason,

Thanks for the report.  I'm considering this a bug, not a feature request.  We're working on a theme release to go out next week.  I'll see if we can get this out in that release.
